---
galaxy_info:
  namespace: jiholland
  role_name: backup
  author: JÃ¸rn Ivar Holland
  description: "Backup running-configuration to git repository."
  license: BSD-3-Clause
  min_ansible_version: "2.16"
  platforms:
    - name: IOS
      versions:
        - all
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - backup
    - catalyst
    - cisco
    - networking
    - nexus


dependencies: []
